services:
  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    container_name: kong
    user: "${KONG_USER:-kong}"
    profiles: [ "infra","all" ]
    # The following line is only for Linux environments. For a demo or quick test on Windows, please comment out the line below.
    # This is used to add a host entry and route from Kong gateway container to bridge interfaces with the host machine for easier Docker development.
    # For more information, check out Docker's networking architecture.

    #    extra_hosts:
#      - "se347-backend:172.21.0.1"
    environment:
      KONG_DATABASE: "off"
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "${KONG_PROXY_LISTEN:-0.0.0.0:80}"
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_LISTEN:-0.0.0.0:9001}"
      KONG_ADMIN_GUI_LISTEN: "${KONG_ADMIN_GUI_LISTEN:-0.0.0.0:9002}"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yaml"
    networks: [ dev ]
    ports:
      # The following two environment variables default to an insecure value (0.0.0.0)
      # according to the CIS Security test.
      - "${KONG_INBOUND_PROXY_LISTEN:-0.0.0.0}:80:80/tcp"
      - "${KONG_INBOUND_SSL_PROXY_LISTEN:-0.0.0.0}:8443:8443/tcp"
      # Making them mandatory but undefined, like so would be backwards-breaking:
      #       - "${KONG_INBOUND_PROXY_LISTEN?Missing inbound proxy host}:8000:8000/tcp"
      #       - "${KONG_INBOUND_SSL_PROXY_LISTEN?Missing inbound proxy ssl host}:8443:8443/tcp"
      # Alternative is deactivating check 5.13 in the security bench, if we consider Kong's own config to be enough security here

      - "9001:9001/tcp"
      - "9444:9444/tcp"
      - "9002:9002/tcp"
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    read_only: true
    volumes:
      - kong_prefix_vol:${KONG_PREFIX:-/var/run/kong}
      - kong_tmp_vol:/tmp
      - ./kong.yaml:/etc/kong/kong.yaml:ro
#      - ./kong.conf.default:/etc/kong/kong.conf.default:ro
    security_opt:
      - no-new-privileges
  mongodb:
    profiles: [ "infra","all" ]
    image: mongodb/mongodb-community-server:7.0.2-ubi9
    hostname: mongodb
    networks: [ dev ]
    ports:
      - "27017:27017"
  se347-backend:
    profiles: [ "app","all" ]
    image: "ghcr.io/ngodat0103/se347-backend:dev-latest"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_PORT: 5000
        SERVICE_NAME: se347-backend
        VERSION: v1
    container_name: se347-backend
    networks: [ dev ]
#    depends_on:
#      - mongodb
    ports:
      - "5000:5000"
    environment:
      SPRING_PROFILES_ACTIVE: "local-dev"
      SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/se347"
      SPRING_DATA_MONGODB_DATABASE: "se347"
      SPRING_DATA_MONGODB_USERNAME: "dev"
      SPRING_DATA_MONGODB_PASSWORD: "dev"
volumes:
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
networks:
  dev:
    name: dev
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
          gateway: "172.21.0.1"