name: Backend CI
on:
 workflow_dispatch:    
 push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
      - release/*
      - bugfix/*
      - refactor/*
      - chore/*
      - docs/*
      - style/*
      - test/*
    paths:
      - 'backend/src/**'
      - 'backend/Dockerfile'
      - 'backend/pom.xml'
jobs:
  build-and-push:
    name: Build and push with pull request tag
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up buildx
        uses: docker/setup-buildx-action@v3.4.0
      - name: docker login credential
        uses: docker/login-action@v3.2.0
        with:
          logout: false
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/ngodat0103/se347/se347-backend
      - name: build and push
        working-directory: backend 
        run: |
            docker compose --profile app build
            docker compose --profile app push
            docker tag ghcr.io/ngodat0103/se347/se347-backend:dev-latest ghcr.io/ngodat0103/se347/se347-backend:dev-${{ steps.meta.outputs.tags }}
            docker push ghcr.io/ngodat0103/se347/se347-backend:dev-${{ steps.meta.outputs.tags }} 